apiVersion: batch/v1
kind: Job
metadata:
  name: {{ include "deploy.fullname" . }}-job-db-extensions
  annotations:
    helm.sh/hook: post-install,post-upgrade
    helm.sh/hook-weight: "2"
    helm.sh/hook-delete-policy: "before-hook-creation,hook-succeeded"
spec:
  template:
    metadata:
      labels:
        {{- include "deploy.selectorLabels" . | nindent 8 }}
    spec:
      restartPolicy: OnFailure
      containers:
        - name: job-db-users
          image: postgres:alpine
          command: ["/bin/sh"]
          args:
            - "-exc"
            - |
              psql --echo-errors "${POSTGRES_OBJECTS}" <<EOF
                CREATE EXTENSION IF NOT EXISTS postgis;
              EOF
          env:
            - name: POSTGRES_HOST
              value: {{ required "PostgreSQL hostname is required" .Values.db.hostname }}
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: username
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: {{ .Values.db.existingSecret }}
                  key: password
            - name: POSTGRES_OBJECTS
              value: 'postgres://$(POSTGRES_USER):$(POSTGRES_PASSWORD)@$(POSTGRES_HOST):5432/objects'