apiVersion: kubedb.com/v1alpha2
kind: Postgres
metadata:
  name: {{ include "deploy.fullname" . }}-postgresql
spec:
  version: "postgis-10.2"
  storageType: {{ required "PostgreSQL storage type is required" .Values.postgresql.storageType }}
  storage:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: {{ required "PostgreSQL storage size is required" .Values.postgresql.storageSize }}
  terminationPolicy: WipeOut
